### ISSUE TITLE
Combine bug - doesn't count quantity in hand

### ISSUE THREAD

**Issue by ralphhogaboom** [thetealviper/Spigot_PaperMoney#3]
When combining money, the plugin doesn't yet take into account stacked bills. 

Example:

slot 1 contains a single $10 pmoney paper
slot 2 contains two $1 pmoney papers

Moving slot 1 into the off hand, then selecting slot 2 and hitting F will combine them - and make $11, not $12.

Thank you for this feature! This rocks.

**Comment by thetealviper** [comment]
Fixed in V1.18.1.b.5. Thanks for reporting clearly :)
